// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RPC/HtnWalletd/HtnWalletd.proto
// </auto-generated>
// Original file comments:
// https://raw.githubusercontent.com/Hoosatnet/Hoosatd/master/cmd/Kaspawallet/daemon/pb/HtnWalletd.proto
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

namespace Miningcore.Blockchain.Hoosat.HtnWalletd {

  using grpc = global::Grpc.Core;

  public partial class HtnWalletdRPC
  {
    public HtnWalletdRPC(string __ServiceName)
    {
      this.__Method_GetBalance = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetBalance",
        __Marshaller_HtnWalletdRPC_GetBalanceRequest,
        __Marshaller_HtnWalletdRPC_GetBalanceResponse);

      this.__Method_GetExternalSpendableUTXOs = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetExternalSpendableUTXOs",
        __Marshaller_HtnWalletdRPC_GetExternalSpendableUTXOsRequest,
        __Marshaller_HtnWalletdRPC_GetExternalSpendableUTXOsResponse);

      this.__Method_CreateUnsignedTransactions = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateUnsignedTransactions",
        __Marshaller_HtnWalletdRPC_CreateUnsignedTransactionsRequest,
        __Marshaller_HtnWalletdRPC_CreateUnsignedTransactionsResponse);

      this.__Method_ShowAddresses = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ShowAddresses",
        __Marshaller_HtnWalletdRPC_ShowAddressesRequest,
        __Marshaller_HtnWalletdRPC_ShowAddressesResponse);

      this.__Method_NewAddress = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "NewAddress",
        __Marshaller_HtnWalletdRPC_NewAddressRequest,
        __Marshaller_HtnWalletdRPC_NewAddressResponse);

      this.__Method_Shutdown = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Shutdown",
        __Marshaller_HtnWalletdRPC_ShutdownRequest,
        __Marshaller_HtnWalletdRPC_ShutdownResponse);

      this.__Method_Broadcast = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Broadcast",
        __Marshaller_HtnWalletdRPC_BroadcastRequest,
        __Marshaller_HtnWalletdRPC_BroadcastResponse);

      this.__Method_Send = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_HtnWalletdRPC_SendRequest,
        __Marshaller_HtnWalletdRPC_SendResponse);

      this.__Method_Sign = new grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Sign",
        __Marshaller_HtnWalletdRPC_SignRequest,
        __Marshaller_HtnWalletdRPC_SignResponse);
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest> __Marshaller_HtnWalletdRPC_GetBalanceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse> __Marshaller_HtnWalletdRPC_GetBalanceResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest> __Marshaller_HtnWalletdRPC_GetExternalSpendableUTXOsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse> __Marshaller_HtnWalletdRPC_GetExternalSpendableUTXOsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest> __Marshaller_HtnWalletdRPC_CreateUnsignedTransactionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse> __Marshaller_HtnWalletdRPC_CreateUnsignedTransactionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest> __Marshaller_HtnWalletdRPC_ShowAddressesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse> __Marshaller_HtnWalletdRPC_ShowAddressesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest> __Marshaller_HtnWalletdRPC_NewAddressRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse> __Marshaller_HtnWalletdRPC_NewAddressResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest> __Marshaller_HtnWalletdRPC_ShutdownRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse> __Marshaller_HtnWalletdRPC_ShutdownResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest> __Marshaller_HtnWalletdRPC_BroadcastRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse> __Marshaller_HtnWalletdRPC_BroadcastResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest> __Marshaller_HtnWalletdRPC_SendRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse> __Marshaller_HtnWalletdRPC_SendResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest> __Marshaller_HtnWalletdRPC_SignRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse> __Marshaller_HtnWalletdRPC_SignResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse> __Method_GetBalance { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse> __Method_GetExternalSpendableUTXOs { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse> __Method_CreateUnsignedTransactions { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse> __Method_ShowAddresses { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse> __Method_NewAddress { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse> __Method_Shutdown { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse> __Method_Broadcast { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse> __Method_Send { get; private set; }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest, global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse> __Method_Sign { get; private set; }

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Miningcore.Blockchain.Hoosat.HtnWalletd.HtnWalletdReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for HtnWalletdRPC</summary>
    public partial class HtnWalletdRPCClient : grpc::ClientBase<HtnWalletdRPCClient>
    {
      public HtnWalletdRPC __HtnWalletdRPC { get; private set; }

      /// <summary>Creates a new client for HtnWalletdRPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public HtnWalletdRPCClient(HtnWalletdRPC __HtnWalletdRPC, grpc::ChannelBase channel) : base(channel)
      {
        this.__HtnWalletdRPC = __HtnWalletdRPC;
      }
      /// <summary>Creates a new client for HtnWalletdRPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public HtnWalletdRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected HtnWalletdRPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected HtnWalletdRPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse GetBalance(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBalance(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse GetBalance(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_GetBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse> GetBalanceAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBalanceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceResponse> GetBalanceAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_GetBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse GetExternalSpendableUTXOs(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetExternalSpendableUTXOs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse GetExternalSpendableUTXOs(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_GetExternalSpendableUTXOs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse> GetExternalSpendableUTXOsAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetExternalSpendableUTXOsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsResponse> GetExternalSpendableUTXOsAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.GetExternalSpendableUTXOsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_GetExternalSpendableUTXOs, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse CreateUnsignedTransactions(global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUnsignedTransactions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse CreateUnsignedTransactions(global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_CreateUnsignedTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse> CreateUnsignedTransactionsAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateUnsignedTransactionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsResponse> CreateUnsignedTransactionsAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.CreateUnsignedTransactionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_CreateUnsignedTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse ShowAddresses(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowAddresses(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse ShowAddresses(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_ShowAddresses, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse> ShowAddressesAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShowAddressesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesResponse> ShowAddressesAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShowAddressesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_ShowAddresses, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse NewAddress(global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NewAddress(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse NewAddress(global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_NewAddress, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse> NewAddressAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NewAddressAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressResponse> NewAddressAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.NewAddressRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_NewAddress, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse Shutdown(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Shutdown(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse Shutdown(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_Shutdown, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse> ShutdownAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShutdownAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownResponse> ShutdownAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.ShutdownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_Shutdown, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse Broadcast(global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Broadcast(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse Broadcast(global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_Broadcast, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse> BroadcastAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BroadcastAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastResponse> BroadcastAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.BroadcastRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_Broadcast, null, options, request);
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse Send(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse Send(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_Send, null, options, request);
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse> SendAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendResponse> SendAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SendRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_Send, null, options, request);
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse Sign(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Sign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse Sign(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__HtnWalletdRPC.__Method_Sign, null, options, request);
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse> SignAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignResponse> SignAsync(global::Miningcore.Blockchain.Hoosat.HtnWalletd.SignRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__HtnWalletdRPC.__Method_Sign, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override HtnWalletdRPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HtnWalletdRPCClient(configuration);
      }
    }

  }
}
#endregion
