// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RPC/htnd/messages.proto
// </auto-generated>
// Original file comments:
// https://raw.githubusercontent.com/Hoosatnet/htnd/master/infrastructure/network/netadapter/server/grpcserver/protowire/messages.proto
// RPC-related types. Request messages, response messages, and dependant types.
//
// Clients are expected to build RequestMessages and wrap them in HtndMessage. (see messages.proto)
//
// Having received a RequestMessage, (wrapped in a HtndMessage) the RPC server will respond with a
// ResponseMessage (likewise wrapped in a HtndMessage) respective to the original RequestMessage.
//
// **IMPORTANT:** This API is a work in progress and is subject to break between versions.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

namespace Miningcore.Blockchain.Hoosat.Htnd {

  using grpc = global::Grpc.Core;

  public partial class htndP2P
  {
    public htndP2P(string __ServiceName)
    {
      this.__Method_MessageStream = new grpc::Method<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "MessageStream",
        __Marshaller_protowire_HtndMessage,
        __Marshaller_protowire_HtndMessage);
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> __Marshaller_protowire_HtndMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> __Method_MessageStream { get; private set; }

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Miningcore.Blockchain.Hoosat.Htnd.MessagesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for htndP2P</summary>
    public partial class htndP2PClient : grpc::ClientBase<htndP2PClient>
    {
      public htndP2P __htndP2P { get; private set; }

      /// <summary>Creates a new client for htndP2P</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public htndP2PClient(htndP2P __htndP2P, grpc::ChannelBase channel) : base(channel)
      {
        this.__htndP2P = __htndP2P;
      }
      /// <summary>Creates a new client for htndP2P that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public htndP2PClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected htndP2PClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected htndP2PClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> MessageStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> MessageStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__htndP2P.__Method_MessageStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>htndP2P</c>, <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override htndP2PClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new htndP2PClient(configuration);
      }
    }

  }
  public partial class HtndRPC
  {
    public HtndRPC(string __ServiceName)
    {
      this.__Method_MessageStream = new grpc::Method<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "MessageStream",
        __Marshaller_protowire_HtndMessage,
        __Marshaller_protowire_HtndMessage);
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> __Marshaller_protowire_HtndMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public grpc::Method<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> __Method_MessageStream { get; private set; }

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Miningcore.Blockchain.Hoosat.Htnd.MessagesReflection.Descriptor.Services[1]; }
    }

    /// <summary>Client for HtndRPC</summary>
    public partial class HtndRPCClient : grpc::ClientBase<HtndRPCClient>
    {
      public HtndRPC __HtndRPC { get; private set; }

      /// <summary>Creates a new client for HtndRPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public HtndRPCClient(HtndRPC __HtndRPC, grpc::ChannelBase channel) : base(channel)
      {
        this.__HtndRPC = __HtndRPC;
      }
      /// <summary>Creates a new client for HtndRPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public HtndRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected HtndRPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected HtndRPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> MessageStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage, global::Miningcore.Blockchain.Hoosat.Htnd.HtndMessage> MessageStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__HtndRPC.__Method_MessageStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override HtndRPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HtndRPCClient(configuration);
      }
    }

  }
}
#endregion
